title: My creative portfolio
author: Henrik Kimlen
description: All the different art I made in my life collected here in one place
theme: minima

# Instellingen voor navigatie en links
header_pages:
  - index.md
  - music.md
  - art.md
  - writing.md
  - videos.md
